"""
Claims_search_api.claims_search_node

LangGraph node wrapper that integrates the claims search pipeline
into the existing graph flow.

This node is called instead of call_claims_tool when the upstream
intent / domain corresponds to claim_history_search. It reads state
the same way as call_claims_tool, performs the upstream member-history
fetch and the in-process query filter, and writes back a tool_results
dict in the same shape so the existing response_agent can summarize it.

Important design notes:
  • The /claims/search endpoint already returns ALL claims for the
    member identified by the supplied claim_id (Step 1). No second
    API call is needed to "expand" by member CAGM — the first call
    already contains the full history.  (Decision confirmed by the
    product owner; the 2-step expansion has been removed.)
  • This node DOES NOT generate a final response by itself — it leaves
    that to agents/response_agent.py, which has a dedicated
    claim-history prompt branch that runs after PII pre/post-checks.

Flow:
  confidence_checker → build_context → [router] → call_claims_search_node
    → response_safety_pii_precheck → response_agent → ...
"""

import traceback
from typing import Dict, Any

from core.logger import get_logger
from core.logging_context import extract_logging_context
from Claims_search_api.search import generalized_claims_query
from Claims_search_api.llm_formatter import format_claims_for_llm
from Claims_search_api.api_utils import (
    extract_list_api_response_structure,
    extract_member_cagm_from_response,
)

logger = get_logger(__name__)


# Cap on the number of claims passed to the LLM after filtering.
# The full /claims/search response can run into tens of thousands of
# rows for active members; even after the in-process query filter we
# clamp the LLM-visible context here to keep prompt size predictable.
_MAX_CLAIMS_FOR_LLM = 50


def _coerce_claim_id(state: Dict[str, Any]) -> str:
    """
    Pull a single claim_id out of the various shapes the upstream nodes
    may have stored it in.  Returns "" when nothing is available.
    """
    entities = state.get("entities") or {}
    extracted_slots = state.get("extracted_slots") or {}
    user_info = state.get("user_info") or {}

    candidates = (
        entities.get("claim_ids"),
        entities.get("claim_id"),
        entities.get("claimNumber"),
        entities.get("claim_number"),
        extracted_slots.get("claim_ids"),
        extracted_slots.get("claim_id"),
        extracted_slots.get("claimNumber"),
        extracted_slots.get("claim_number"),
        user_info.get("claim_id"),
    )

    for c in candidates:
        if not c:
            continue
        if isinstance(c, list):
            if c:
                return str(c[0]).strip()
        else:
            return str(c).strip()
    return ""


async def call_claims_search_node(state: Dict[str, Any]) -> Dict[str, Any]:
    """
    LangGraph node: runs the claims search pipeline.

    Reads from state:
        - text / user_input: the user's natural-language question
        - entities / extracted_slots: should contain a claim_number
        - user_info: auth_token, x_api_key, x_clientrefid

    Writes to state:
        - tool_results: {
              "tool_name": "claims_search",
              "status": "success" | "failure",
              "data": {
                  "claims": [...],            # filtered, LLM-ready
                  "totalCount": int,          # raw count from API
                  "filteredCount": int,
                  "memberInfo": {...},
                  "_masked_response": str,    # compact text for LLM
                  "is_claim_history_search": True,
              },
              ...
          }

    The response itself is generated by the standard response_agent_node
    using its claim-history prompt branch (triggered by the
    `is_claim_history_search` flag inside data).
    """
    node_name = "call_claims_search"
    log_ctx = extract_logging_context(state) if isinstance(state, dict) else {}

    logger.info("🔍 Node: Call Claims Search (member history pipeline)")

    # ------------------------------------------------------------------
    # 1. Resolve claim_id + auth headers
    # ------------------------------------------------------------------
    # Prefer the ORIGINAL user query (pre-orchestrator) for filtering so
    # that the orchestrator's appended "for claim NNN…" doesn't leak into
    # the search heuristics (where it can be misread as a drug name).
    metadata = state.get("metadata") or {}
    user_query = (
        metadata.get("original_text")
        or state.get("user_input")
        or state.get("text")
        or ""
    )
    user_info = state.get("user_info") or {}
    claim_id = _coerce_claim_id(state)

    if not claim_id:
        logger.warning("[ClaimsSearch] No claim_id found in entities/slots/user_info")
        return {
            "tool_results": {
                "tool_name": "claims_search",
                "status": "failure",
                "success": False,
                "error": "No claim ID provided",
                "data": {
                    "is_claim_history_search": True,
                    "claims": [],
                    "totalCount": 0,
                    "filteredCount": 0,
                },
            },
            "needs_clarification": True,
        }

    bearer_token = user_info.get("auth_token", "")
    x_api_key = user_info.get("x_api_key", "")
    x_clientrefid = user_info.get("x_clientrefid", "")

    if not bearer_token:
        logger.warning("[ClaimsSearch] No auth token in user_info")
        return {
            "tool_results": {
                "tool_name": "claims_search",
                "status": "failure",
                "success": False,
                "error": "Missing authorization token",
                "data": {
                    "is_claim_history_search": True,
                    "claims": [],
                    "totalCount": 0,
                    "filteredCount": 0,
                },
            },
        }

    try:
        # --------------------------------------------------------------
        # 2. Step 1 (and only) API call: /claims/search by claim_id
        #    The upstream API already returns ALL claims for the member
        #    identified by this claim_id, so there is no Step 2.
        # --------------------------------------------------------------
        logger.info(f"[ClaimsSearch] Fetching member claim history (claim_id={claim_id})")
        api_response = await extract_list_api_response_structure(
            claim_id=claim_id,
            bearer_token=bearer_token,
            x_api_key=x_api_key,
            x_clientrefid=x_clientrefid,
        )
        claims = api_response.get("claims", []) or []
        total_count = len(claims)

        if not claims:
            return {
                "tool_results": {
                    "tool_name": "claims_search",
                    "status": "success",
                    "success": True,
                    "data": {
                        "is_claim_history_search": True,
                        "claims": [],
                        "totalCount": 0,
                        "filteredCount": 0,
                        "_masked_response": "No claims found for the provided claim number.",
                    },
                },
            }

        logger.info(f"[ClaimsSearch] Fetched {total_count} claim(s) from API")

        # --------------------------------------------------------------
        # 3. Extract member info (for downstream display / debugging)
        # --------------------------------------------------------------
        member_info = extract_member_cagm_from_response(api_response)

        # --------------------------------------------------------------
        # 4. Filter claims by user query (drug name, reject code, status, …)
        # --------------------------------------------------------------
        filtered_claims = generalized_claims_query(claims, user_query) or []
        filtered_count = len(filtered_claims)
        # Hard cap to keep LLM prompt size manageable
        if filtered_count > _MAX_CLAIMS_FOR_LLM:
            logger.info(
                f"[ClaimsSearch] Capping {filtered_count} → {_MAX_CLAIMS_FOR_LLM} "
                f"claims for the LLM context"
            )
            filtered_claims = filtered_claims[:_MAX_CLAIMS_FOR_LLM]

        logger.info(
            f"[ClaimsSearch] Filtered {total_count} → {filtered_count} claim(s) "
            f"(LLM-visible: {len(filtered_claims)}) for query: {user_query!r}"
        )

        # --------------------------------------------------------------
        # 5. Format trimmed/filtered payload for the LLM
        # --------------------------------------------------------------
        filtered_response = {
            **api_response,
            "claims": filtered_claims,
            "totalCount": filtered_count,
        }
        llm_context = format_claims_for_llm(
            filtered_response,
            user_query=None,             # already filtered; do not re-filter
            is_member_history=True,
            max_claims=_MAX_CLAIMS_FOR_LLM,
        )

        logger.info(
            f"[ClaimsSearch] LLM context size: {len(llm_context)} chars "
            f"({len(filtered_claims)} claims)"
        )

        # --------------------------------------------------------------
        # 6. Hand back to response_agent via tool_results
        # --------------------------------------------------------------
        return {
            "tool_results": {
                "tool_name": "claims_search",
                "status": "success",
                "success": True,
                "data": {
                    "is_claim_history_search": True,
                    "claims": filtered_claims,
                    "totalCount": total_count,
                    "filteredCount": filtered_count,
                    "memberInfo": member_info,
                    "_masked_response": llm_context,
                },
            },
        }

    except Exception as e:
        tb = traceback.format_exc()
        logger.error(f"[ClaimsSearch] Node error: {e}\n{tb}")
        return {
            "tool_results": {
                "tool_name": "claims_search",
                "status": "failure",
                "success": False,
                "error": str(e),
                "data": {
                    "is_claim_history_search": True,
                    "claims": [],
                    "totalCount": 0,
                    "filteredCount": 0,
                },
            },
        }
