import asyncio
from api_utils import extract_list_api_response_structure, extract_member_cagm_from_response, extract_member_history_using_cagm_details

token = "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6InRBSjlZYmlRbXFwYm9vQU5razdsR2RJd04zdER0NnJNUkxYSG0xWUE4SlUiLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJkZWYzNWU5Ni0xZWIwLTQ4NzctOTdlMS01MTE5OTJhMjQ4YmMiLCJpc3MiOiJodHRwczovL25nYW15cGJtbm9ucHJvZC5iMmNsb2dpbi5jb20vMmEyNzYyZTctZDU2Zi00N2FiLWE3MmEtZGYwMTAyYzQ1NzlhL3YyLjAvIiwiZXhwIjoxNzc2NjY0ODc0LCJuYmYiOjE3NzY2NjEyNzQsInRpZCI6ImZhYmI2MWI4LTNhZmUtNGU3NS1iOTM0LWE0N2Y3ODJiOGNkNyIsImdpdmVuX25hbWUiOiJ2YW1zaGkiLCJmYW1pbHlfbmFtZSI6ImtyaXNobmEiLCJlbWFpbCI6IlZhbXNoaS5LcmlzaG5hMkBjdnNoZWFsdGguY29tIiwibmFtZSI6ImtyaXNobmEsIHZhbXNoaSIsImlkcCI6Imh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbS9mYWJiNjFiOC0zYWZlLTRlNzUtYjkzNC1hNDdmNzgyYjhjZDcvdjIuMCIsInN1YiI6IjJiOGJmNmQ3LTk5MzYtNGVjMS1hYzcwLTliMDlkN2MyZGI2NiIsIm5vbmNlIjoiYjJSUmMyNVBXSE53ZUZkWVNrcENaWFZvVTJSSFgxWkhSMGhOYTFFelIyZG1OMVJQY1U1ZlRGRnNZMlIzIiwic2NwIjoiVXNlci5SZWFkIiwiYXpwIjoiZGVmMzVlOTYtMWViMC00ODc3LTk3ZTEtNTExOTkyYTI0OGJjIiwidmVyIjoiMS4wIiwiaWF0IjoxNzc2NjYxMjc0fQ.GWw6g1PH3RKgvcNey03jXLuZt728EQpwgMmIAE-GZpNwurQpf-00DndlG9nYSnyFffMowSOxv7wsJpMEhKFEjJyEQ78nSRYS9s8fDm31UNOl8cQLqfYTarY11ghDAIZxRyemiPxkBjfScN5Di47XQR3wsNHUPsAsMSafPQDmhrMtjkaR5ArbffpRhEzpfNKW75KHRmz3YmRR8hkSSY6NbEPzCP4aQ_OM6zNQkNvPRt-gzCgvzFjZud5vbkUnTzUX-BahgQ30E9WVKsF66SNCFtyBCSf7DeHHin0O1cdnpRbfVhMWmLO5cuMG-9UoZXO25CSvh9c4XEpPXO7vB9wDMQ"
x_api_key = "fbbae75e-cd91-47a5-bb65-b68f525a66e3"
x_clientrefid = "17457c7d-6e27-407a-ae5b-c25cc1af8843"

async def main():
    claim_id = "260302639954275"
    response = await extract_list_api_response_structure(claim_id, token, x_api_key, x_clientrefid)
    print("Full API response:")
    print(response)
    member_info = extract_member_cagm_from_response(response)
    print("\nExtracted member/CAGM details:")
    print(member_info)
    print("\nTesting extract_member_history_using_cagm_details:")
    member_history = await extract_member_history_using_cagm_details(response, member_info)
    print(member_history)

if __name__ == "__main__":
    asyncio.run(main())
