class embeddingVars:
    CVS_INTENT_EXAMPLES = {
    
    "approval_info": [
        "Provide a detailed approval summary for this claim.",
        "Show which plan overrides were triggered during adjudication.",
        "Retrieve the transition fill status for this claim.",
        "Display the specific transition fill type applied to this claim.",
        "Tell me what plan options were active at the time of processing.",
        "Generate a report on why accumulations were not considered for this claim.",
        "Fetch the BPG configuration used to approve this claim.",
        "Give me the override details for the most recent claim.",
        "Provide information on any member PA or Smart PA applied.",
        "Show the logic behind the approval decision for this claim.",
        "Display all plan configuration overrides that affected this claim.",
        "Retrieve the adjudication pathway for this claim.",
        "Generate a TF summary for this claim.",
        "Show transition fill details for this claim.",
        "Provide TF status for this claim.",
        "Display transition fill approval information.",
        "Fetch TF configuration for this claim.",
        "Tell me the TF eligibility for this member.",
        "Give me transition fill override details.",
        "Retrieve the TF type applied to this claim.",
    ],

    "audit_info": [
        "Generate the audit log for this claim",
        "Show me the change history for this claim",
        "Display the audit information for this claim",
        "Give me the modification record for this claim",
        "Tell me the audit details for this claim",
        "Provide the full audit report for this claim",
        "Retrieve the change log for this claim",
        "Fetch the update history for this claim",
        "Generate the modification audit for this claim",
        "Show the claim history for this claim",
        "Display the audit trail for this claim",
        "Give me the edit history for this claim",
        "Tell me the claim modification details",
        "Provide the audit summary for this claim",
        "Retrieve the claim audit for this claim",
        "Fetch the claim modification log",
        "Generate the history of changes for this claim",
        "Show me the audit record for this claim",
        "Display the modification details for this claim",
        "Give me the audit information for this claim",
    ],

    "beneficiary_info": [
        "Generate the current benefit phase for this claim.",
        "Show the member's coverage details associated with this claim.",
        "Display the accumulation status for the member on this claim.",
        "Give me the member's benefit type for this claim.",
        "Tell me if medical dollars are included in the member's accumulation.",
        "Provide the linked LOE information for the member on this claim.",
        "Retrieve the member's coverage tier for this claim.",
        "Fetch the benefit phase the member is currently in for this claim.",
        "Generate the member's eligibility information for this claim.",
        "Show the member's plan details for this claim.",
        "Display whether medical expenses contribute to the accumulation.",
        "Give me the member's insurance coverage type.",
        "Tell me the current benefit phase for the member on this claim.",
        "Provide the linked member levels of evidence (LOE).",
        "Retrieve the member's benefit eligibility.",
        "Fetch the member's coverage information for this prescription.",
        "Generate a summary of the member's benefit phase.",
        "Show the member's accumulation rules for this claim.",
        "Display the member's coverage classification.",
        "Give me the member's benefit plan configuration.",
    ],

    "claim_status": [
        "Generate a full claim summary for this claim.",
        "Show the current status of this claim.",
        "Display all details for this claim.",
        "Give me the processing status for this claim.",
        "Tell me the progress of this claim.",
        "Provide the adjudication outcome for this claim.",
        "Retrieve the complete claim record.",
        "Fetch the claim details for this claim.",
        "Generate a breakdown of this claim.",
        "Show the status update for this claim.",
        "Give me a claim summary for this claim.",
        "Generate a claim summary.",
        "Show claim summary for this claim.",
        "Provide a summary of this claim.",
        "What happened on claim sequences?",
        "Compare this claim to another claim.",
        "Tell me about this claim.",
        "Show the full record for this claim.",
        "Display the adjudication details for this claim.",
        "Give me the comprehensive summary.",
    ],

    "cob_info": [
        "Generate a COB summary for this claim.",
        "Show the coordination of benefits details for this claim.",
        "Display the other insurance information for this claim.",
        "Give me the COB pricing breakdown for this claim.",
        "Tell me how other insurance affected this claim.",
        "Provide the secondary insurance details for this claim.",
        "Retrieve the COB calculation for this claim.",
        "Fetch the coordination details for this claim.",
        "Generate the COB pricing information.",
        "Show how coordination of benefits was applied to this claim.",
        "Display the other payer information for this claim.",
        "Give me the dual coverage details for this claim.",
        "Tell me the COB setup for this claim.",
        "Provide the secondary payer information.",
        "Retrieve the coordination of benefits report.",
        "Fetch the other insurance impact on this claim.",
        "Generate the COB adjudication details.",
        "Show the primary and secondary insurance breakdown.",
        "Display the COB configuration for this claim.",
        "Give me the coordination pricing summary.",
    ],

    "compound_info": [
        "Generate the compound medication details for this claim.",
        "Show the ingredient breakdown for this claim.",
        "Display the MIC information for this claim.",
        "Give me the compound ingredient costs for this claim.",
        "Tell me if this claim is for a compounded medication.",
        "Provide the funded and unfunded costs for the compound in this claim.",
        "Retrieve the ingredient list for this compound claim.",
        "Fetch the compound drug details for this claim.",
        "Generate the MIC cost breakdown.",
        "Show the individual ingredient pricing.",
        "Display whether this is a compound prescription.",
        "Give me the compound formulation details.",
        "Tell me the ingredient costs for the compounded medication.",
        "Provide the compound medication summary.",
        "Retrieve the MIC details and ingredient breakdown.",
        "Fetch the compound pricing information.",
        "Generate the ingredient cost report.",
        "Show the funded versus unfunded ingredient costs.",
        "Display the compound claim details.",
        "Give me the MIC summary for this prescription.",
    ],

    "date_range_claims": [
        "Generate a list of claims that contributed to the deductible.",
        "Show all claims for this drug in the member's history.",
        "Display claims from the past six months.",
        "Give me the claims that affected the out-of-pocket maximum.",
        "Tell me which claims contributed to the member's accumulation.",
        "Provide a history of all claims for this medication.",
        "Retrieve claims within a specific date range.",
        "Fetch the member's claim history for this drug.",
        "Generate a report of claims affecting deductible and OOP.",
        "Show the claims that impacted the member's benefit phase.",
        "Display all prescription claims for this member.",
        "Give me the list of claims for this year.",
        "Tell me the claims that contributed to cost-sharing.",
        "Provide the claim history for this member and drug.",
        "Retrieve all claims that affected the accumulation.",
        "Fetch the deductible-contributing claims.",
        "Generate a summary of claims over the last quarter.",
        "Show the member's prescription history.",
        "Display the claims from January to March.",
        "Give me all claims for this drug type.",
    ],

    "daw_info": [
        "Generate the DAW status for this claim.",
        "Show the dispense as written details for this claim.",
        "Display whether brand name was required for this claim.",
        "Give me the DAW code for this prescription.",
        "Tell me if generic substitution was allowed for this claim.",
        "Provide the brand versus generic information for this claim.",
        "Retrieve the DAW indicator for this claim.",
        "Fetch the dispense as written status.",
        "Generate the substitution details for this prescription.",
        "Show whether brand was medically necessary.",
        "Display the DAW selection for this claim.",
        "Give me the brand name requirement details.",
        "Tell me if a generic could be substituted.",
        "Provide the DAW configuration for this claim.",
        "Retrieve the dispense as written code.",
        "Fetch the brand versus generic status.",
        "Generate the substitution rules for this claim.",
        "Show the DAW designation.",
        "Display the brand requirement information.",
        "Give me the generic availability status.",
    ],

    "drug_info": [
        "Generate the drug status for this claim.",
        "Show the medication details for this claim.",
        "Display the drug information for this prescription.",
        "Give me the formulary status for the drug in this claim.",
        "Tell me which drug was dispensed for this claim.",
        "Provide the medication classification for this claim.",
        "Retrieve the drug setup used in RxClaim for this claim.",
        "Fetch the drug name and NDC for this prescription.",
        "Generate the drug category details.",
        "Show the formulary position for this medication.",
        "Display the drug type and classification.",
        "Give me the GPI and therapeutic class.",
        "Tell me the drug status assigned by RxClaim.",
        "Provide the medication tier information.",
        "Retrieve the drug details for this claim.",
        "Fetch the drug configuration from the claim.",
        "Generate the formulary report for this drug.",
        "Show the drug classification details.",
        "Display the medication status.",
        "Give me the drug tier and formulary placement.",
    ],

    "drug_interaction_info": [
        "Generate the DUR edits applied to this claim.",
        "Show the drug utilization review details for this claim.",
        "Display the DUR outcomes for this prescription.",
        "Give me the interaction alerts for this claim.",
        "Tell me which DUR edits were triggered for this claim.",
        "Provide the drug interaction warnings.",
        "Retrieve the DUR edit results for this claim.",
        "Fetch the utilization review information.",
        "Generate the DUR report for this claim.",
        "Show the drug interaction outcomes.",
        "Display the clinical edits that were triggered.",
        "Give me the DUR override details.",
        "Tell me the utilization review results.",
        "Provide the interaction screening outcomes.",
        "Retrieve the DUR edit codes for this claim.",
        "Fetch the drug utilization details.",
        "Generate the interaction alert summary.",
        "Show the clinical screening results.",
        "Display the DUR processing details.",
        "Give me the drug interaction report.",
    ],

    "fill_date_info": [
        "Generate the fill date for this claim.",
        "Show when the prescription was filled for this claim.",
        "Display the dispense date for this claim.",
        "Give me the service date for this claim.",
        "Tell me when the medication was dispensed.",
        "Provide the date the prescription was filled.",
        "Retrieve the fill date details for this claim.",
        "Fetch the dispensing date for this prescription.",
        "Generate the date of service for this claim.",
        "Show the fill date information.",
        "Display when the pharmacy filled this prescription.",
        "Give me the date the medication was picked up.",
        "Tell me the dispensing date for this claim.",
        "Provide the fill date and time.",
        "Retrieve the service date for this prescription.",
        "Fetch the date when this was filled.",
        "Generate the dispensing date report.",
        "Show the fill timestamp.",
        "Display the prescription fill date.",
        "Give me the date of fill for this claim.",
    ],

    "generic_availability": [
        "Generate a list of generic alternatives for this claim.",
        "Show the substitute medications available.",
        "Display the generic options for this drug.",
        "Give me the alternative medications for this claim.",
        "Tell me what generic drugs are available.",
        "Provide the therapeutic alternatives.",
        "Retrieve the substitute drug list.",
        "Fetch the generic availability information.",
        "Generate the alternative medication options.",
        "Show the formulary alternatives for this drug.",
        "Display the generic substitutes.",
        "Give me the list of cheaper drug options.",
        "Tell me the available generic medications.",
        "Provide the therapeutic equivalent drugs.",
        "Retrieve the substitute options for this prescription.",
        "Fetch the generic alternative details.",
        "Generate the drug substitution recommendations.",
        "Show the formulary-approved alternatives.",
        "Display the generic medication options.",
        "Give me the substitute drug information.",
    ],

    "government_claim_type": [
        "Generate the government claim type for this claim.",
        "Show whether this is a Medicare or Medicaid claim.",
        "Display the government program classification for this claim.",
        "Give me the claim type designation.",
        "Tell me if this claim is a government claim.",
        "Provide the Medicare or Medicaid status.",
        "Retrieve the government program details.",
        "Fetch the claim classification for this claim.",
        "Generate the program type information.",
        "Show the government claim designation.",
        "Display whether this is a public insurance claim.",
        "Give me the Medicare type for this claim.",
        "Tell me the government program classification.",
        "Provide the claim type (Medicare Part D, Medicaid, etc.).",
        "Retrieve the government claim category.",
        "Fetch the public program details.",
        "Generate the claim type report.",
        "Show the government insurance classification.",
        "Display the Medicare or Medicaid designation.",
        "Give me the program type for this claim.",
    ],

    "greeting": [
        "Generate a welcome message",
        "Show me the greeting",
        "Display hello",
        "Give me a hi",
        "Tell me hello there",
        "Provide greetings",
        "Retrieve the welcome",
        "Fetch a greeting",
        "Generate hello",
        "Show a welcome",
        "Display good morning",
        "Give me a good afternoon",
        "Tell me good evening",
        "Provide a hi",
        "Retrieve greetings",
        "Fetch hello",
        "Generate a hi there",
        "Show good day",
        "Display howdy",
        "Give me a hey",
    ],

    "help": [
        "Generate instructions on how to submit a claim properly.",
        "Show me the steps to avoid claim rejection.",
        "Display the correct submission process.",
        "Give me guidance on filing claims.",
        "Tell me how to submit claims without errors.",
        "Provide the proper claim submission procedure.",
        "Retrieve the instructions for correct claim filing.",
        "Fetch the help documentation for claim submission.",
        "Generate the guidelines for avoiding rejections.",
        "Show the best practices for claim submission.",
        "Display the claim submission checklist.",
        "Give me the process to follow for successful claims.",
        "Tell me the requirements for claim acceptance.",
        "Provide the claim submission help.",
        "Retrieve the instructions to prevent denials.",
        "Fetch the submission guidelines.",
        "Generate the correct filing procedures.",
        "Show the claim submission protocol.",
        "Display the help for proper claim filing.",
        "Give me the instructions for avoiding errors.",
    ],

    "mail_order_info": [
        "Generate the mail order status for this claim.",
        "Show whether this was a home delivery prescription.",
        "Display the delivery method for this claim.",
        "Give me the mail order details for this claim.",
        "Tell me if this prescription was shipped.",
        "Provide the home delivery information.",
        "Retrieve the mail order status.",
        "Fetch the delivery type for this prescription.",
        "Generate the shipping details for this claim.",
        "Show whether this was a mail order claim.",
        "Display the delivery method used.",
        "Give me the home delivery status.",
        "Tell me if this was sent by mail.",
        "Provide the mail order designation.",
        "Retrieve the shipping information.",
        "Fetch the delivery details for this claim.",
        "Generate the mail order report.",
        "Show the home delivery status.",
        "Display whether this was mailed.",
        "Give me the delivery method information.",
    ],

    "medicare_part_d": [
        "Generate a Medicare Part D summary for this claim.",
        "Show the PDE details for this claim.",
        "Display the MEDD pricing including LICS and N1s.",
        "Give me the Part D information for this claim.",
        "Tell me the Medicare coverage details for this claim.",
        "Provide the PDE report for this prescription.",
        "Retrieve the Part D summary.",
        "Fetch the Medicare pricing details.",
        "Generate the LICS and N1 breakdown for this claim.",
        "Show the Part D plan information.",
        "Display the PDE submission details.",
        "Give me the Medicare Part D coverage.",
        "Tell me the MEDD pricing summary.",
        "Provide the Part D benefit details.",
        "Retrieve the PDE information.",
        "Fetch the Medicare coverage report.",
        "Generate the Part D pricing breakdown.",
        "Show the LICS details for this claim.",
        "Display the N1 and MEDD information.",
        "Give me the Medicare Part D summary.",
    ],

    "multi_claim_summary": [
        "Generate a summary of ALL claims for this member",
        "Display the list of MULTIPLE claims associated with this member",
        "Retrieve ALL claim records in the system",
        "Provide details for EVERY claim linked to this member",
        "Show the complete set of ALL claims",
        "Give me a summary of MULTIPLE claims",
        "Tell me about ALL claims under this member",
        "Fetch EVERY claim related to this member",
        "Generate a report of ALL claims in the database",
        "Display ALL available claims for this member",
        "Retrieve ALL claims in the system",
        "Provide a summary of MULTIPLE claims in history",
        "Show the FULL LIST of claims",
        "Give me details for ALL claims",
        "Tell me about MULTIPLE claims",
        "Fetch ALL claim records",
        "List EVERY claim in the database",
        "Display MULTIPLE claims",
        "Retrieve the complete set of ALL claims",
        "Show me ALL claims for this member",
    ],

    "network_info": [
        "Generate the pharmacy network details for this claim.",
        "Show which network was used for this claim.",
        "Display the network information for this prescription.",
        "Give me the pharmacy chain details for this claim.",
        "Tell me which network processed this claim.",
        "Provide the pharmacy network classification.",
        "Retrieve the network type for this claim.",
        "Fetch the pharmacy network information.",
        "Generate the network details used for payment.",
        "Show the pharmacy chain network.",
        "What pharmacy network did the claim pay with?",
        "Which network was used to pay this claim?",
        "Tell me the payment network for this claim.",
        "Show the network that paid for this claim.",
        "What network processed the payment for this claim?",
        "Display the paying network information.",
        "Which pharmacy network handled the payment?",
        "Retrieve the network used for claim payment.",
        "Give me the payment network details.",
        "Show the network that reimbursed this claim.",
    ],

    "out_of_scope": [
        # Clearly off-topic questions (no trigger words like Provide/Show/Display)
        "What's the weather forecast?",
        "I need a pizza recipe",
        "Book me a flight to Hawaii",
        "Sports scores from last night",
        "Latest political news",
        "Best restaurants near me",
        "Stock market performance today",
        "Movie recommendations for tonight",
        "Celebrity gossip updates",
        "Travel tips for Europe",
        "Historical facts about Rome",
        "Science experiments for kids",
        # Question format (interrogative)
        "Why is the sky blue?",
        "What is the weather like today?",
        "How do I cook pasta?",
        "When is the Super Bowl?",
        "Who won the election?",
        "Where can I find good restaurants?",
        "What time does the movie start?",
        "How does gravity work?",
        "Why do birds fly south?",
        "What's the capital of France?",
        # General off-topic
        "Random trivia question",
        "Joke of the day",
        "Music playlist suggestions",
        "Fitness workout routines",
        "Gaming tips and tricks",
        "Fashion advice for summer",
        # Lorem ipsum / Junk text / Gibberish
        "Lorem ipsum dolor sit amet consectetur adipiscing elit",
        "Quisque faucibus ex sapien vitae pellentesque sem placerat",
        "Tempus leo eu aenean sed diam urna tempor pulvinar",
        "Vivamus fringilla lacus nec metus bibendum egestas",
        "Ad litora torquent per conubia nostra inceptos himenaeos",
        "Sed ut perspiciatis unde omnis iste natus error sit voluptatem",
        "Nemo enim ipsam voluptatem quia voluptas sit aspernatur",
        "Neque porro quisquam est qui dolorem ipsum quia dolor",
        "asdfghjkl qwertyuiop zxcvbnm",
        "abcdefghijklmnopqrstuvwxyz random letters",
        "test test test test test test",
        "blah blah blah blah blah",
        "foo bar baz qux quux corge",
        "hello hello hello hello",
        "aaaaaa bbbbbb cccccc dddddd",
        "12345 67890 abcde fghij",
    ],

    "pharmacy_info": [
        "Generate the pharmacy details for this claim.",
        "Show where the prescription was filled.",
        "Display the dispensing pharmacy for this claim.",
        "Give me the pharmacy name where this claim was filled.",
        "Tell me which pharmacy dispensed this prescription.",
        "Provide the pharmacy location information.",
        "Retrieve the dispensing pharmacy details.",
        "Fetch the pharmacy information for this claim.",
        "Generate the store location where this was filled.",
        "Show the pharmacy name and address.",
        "Display the dispensing location.",
        "Give me the CVS store details.",
        "Tell me where the member got this prescription.",
        "Provide the pharmacy NCPDP number.",
        "Retrieve the dispensing pharmacy location.",
        "Fetch the store information.",
        "Generate the pharmacy report.",
        "Show where the medication was dispensed.",
        "Display the pharmacy details.",
        "Give me the filling pharmacy information.",
    ],

    "prescriber_info": [
        "Generate the prescriber details for this claim.",
        "Show who prescribed the medication for this claim.",
        "Display the physician information for this prescription.",
        "Give me the doctor's name for this claim.",
        "Tell me which physician wrote this prescription.",
        "Provide the prescriber NPI for this claim.",
        "Retrieve the ordering provider details.",
        "Fetch the prescriber information.",
        "Generate the physician report for this claim.",
        "Show the doctor's contact information.",
        "Display the prescriber's name and credentials.",
        "Give me the provider details.",
        "Tell me who ordered this medication.",
        "Provide the prescribing physician information.",
        "Retrieve the prescriber NPI and name.",
        "Fetch the doctor's details.",
        "Generate the provider summary.",
        "Show the prescribing physician.",
        "Display the ordering provider information.",
        "Give me the prescriber name.",
    ],

    "pricing_info": [
        "Show the detailed pricing breakdown for this claim.",
        "Provide the copay calculation steps for this claim.",
        "Retrieve the ingredient cost and associated fees for this claim.",
        "Display the manufacturer rebate applied to this claim.",
        "Give me the pricing schedule used for this claim.",
        "Fetch the patient pay details for this claim.",
        "Tell me the final out-of-pocket amount for this claim.",
        "Generate a summary of all pricing components for this claim.",
        "Show the co-pay modifier and its impact on this claim.",
        "Provide the total cost and copay for this claim.",
        "Generate a pricing summary for this claim.",
        "Show pricing summary for this claim.",
        "Display the pricing breakdown.",
        "What is the cost of this claim?",
        "How much did I pay?",
        "Tell me the pricing details.",
        "What's the total cost of my prescriptions?",
        "Provide the pricing summary for the most recent claim.",
        "Retrieve the final copay amount for the last processed claim.",
        "Display the pricing information for this claim.",
    ],

    "prior_auth_info": [
        "Generate the prior authorization details for this claim.",
        "Show the PA status for this claim.",
        "Display the Smart PA information for this claim.",
        "Give me the Member PA details for this claim.",
        "Tell me if prior authorization was required.",
        "Provide the PA number and approval status.",
        "Retrieve the prior auth details for this prescription.",
        "Fetch the authorization information.",
        "Generate the PA summary for this claim.",
        "Show whether PA was approved or denied.",
        "Display the authorization status.",
        "Give me the Smart PA configuration.",
        "Tell me the prior auth requirements.",
        "Provide the Member PA summary.",
        "Retrieve the PA approval details.",
        "Fetch the authorization status for this drug.",
        "Generate the prior authorization report.",
        "Show the PA type and approval.",
        "Display the authorization details.",
        "Give me the prior auth information.",
    ],

    "reimbursement_info": [
        "Generate the reimbursement details for this claim.",
        "Show what was reimbursed for the paper claim.",
        "Display the payment information for this claim.",
        "Give me the reimbursement amount for this claim.",
        "Tell me what was paid for this claim.",
        "Provide the reimbursement breakdown.",
        "Retrieve the payment details.",
        "Fetch the reimbursement information.",
        "Generate the payment summary.",
        "Show the reimbursed amount.",
        "Display the payment calculation.",
        "Give me the reimbursement rationale.",
        "Tell me why this amount was reimbursed.",
        "Provide the payment details for the paper claim.",
        "Retrieve the reimbursement report.",
        "Fetch the payment information.",
        "Generate the reimbursement summary.",
        "Show what the pharmacy was paid.",
        "Display the reimbursement calculation.",
        "Give me the payment breakdown.",
    ],

    "rejection_reasons": [
        "Generate the specific rejection reasons for this claim.",
        "Show the edits that caused this claim to reject.",
        "Display the rejection details for this claim.",
        "Give me the list of rejection codes for this claim.",
        "Tell me why this claim was denied.",
        "Provide the rejection explanation for this claim.",
        "Retrieve the failed edits for this claim.",
        "Fetch the reason codes for the rejection of this claim.",
        "Generate the rejection rationale for this claim.",
        "Show the specific edits that led to the claim rejection.",
        "Display the denial reasons for the current claim.",
        "Give me the claim rejection breakdown.",
        "Tell me which edits triggered the rejection for this claim.",
        "Provide the details on why the claim was not accepted.",
        "Retrieve the rejection information for this claim.",
        "Fetch the failed edit codes for the claim.",
        "Generate a summary of the rejection reasons for the claim.",
        "Show the claim rejection cause.",
        "Display the edits that resulted in the claim denial.",
        "Give me the technical reason for the claim rejection.",
        "What can be done to overcome the rejection?",
        "How to resolve a rejected claim?",
        "Steps to overturn a rejection for this claim.",
        "Options to fix a denied claim.",
    ],

    "reversal_info": [
        "Generate the reversal details for this claim.",
        "Show any adjustments made to this claim.",
        "Display the R&R information for this claim.",
        "Give me the manual adjustment details.",
        "Tell me if this claim was reversed.",
        "Provide the modification history.",
        "Retrieve the reversal and resubmission details.",
        "Fetch the adjustment information.",
        "Generate the R&R report for this claim.",
        "Show any claim modifications.",
        "Display the reversal status.",
        "Give me the adjustment details.",
        "Tell me about any manual changes.",
        "Provide the reversal information.",
        "Retrieve the modification details.",
        "Fetch the R&R status.",
        "Generate the adjustment summary.",
        "Show the claim reversal details.",
        "Display any resubmissions.",
        "Give me the reversal report.",
    ],

    "rx_details": [
        "Generate the RX number for this claim.",
        "Show the prescription details for this claim.",
        "Display the quantity dispensed for this claim.",
        "Give me the days supply for this claim.",
        "Tell me the fill number for this prescription.",
        "Provide the RX details for this claim.",
        "Retrieve the prescription number.",
        "Fetch the quantity and days supply.",
        "Generate the RX information.",
        "Show the prescription fill details.",
        "Display the RX number and fill count.",
        "Give me the dispensing quantity.",
        "Tell me the days supply for this prescription.",
        "Provide the fill number information.",
        "Retrieve the RX details.",
        "Fetch the prescription strength and quantity.",
        "Generate the prescription summary.",
        "Show the RX number.",
        "Display the fill details.",
        "Give me the prescription information.",
    ],

    "settlement_info": [
        "Generate the settlement codes for this claim.",
        "Show the pharmacy response for this claim.",
        "Display the settlement information sent to the pharmacy.",
        "Give me the feedback codes for this claim.",
        "Tell me what was sent back to the pharmacy.",
        "Provide the settlement details.",
        "Retrieve the pharmacy response codes.",
        "Fetch the settlement information.",
        "Generate the settlement report.",
        "Show the response sent to the pharmacy.",
        "Display the settlement codes.",
        "Give me the pharmacy feedback.",
        "Tell me the settlement status.",
        "Provide the response codes.",
        "Retrieve the settlement details.",
        "Fetch the pharmacy response.",
        "Generate the settlement summary.",
        "Show the codes sent to the pharmacy.",
        "Display the settlement feedback.",
        "Give me the response information.",
    ],

    # ──────────────────────────────────────────────────────────────────
    # benefits_api intents  (generic phrasing, no hardcoded IDs)
    # ──────────────────────────────────────────────────────────────────
    "plan_summary": [
        "show the current benefit plan overview for this member",
        "give me a snapshot of the member's active plan",
        "what does this member's benefit plan cover",
        "display the current plan summary",
        "pull up the overview of the member's plan",
        "retrieve a high-level view of the benefits plan",
        "summarize the active benefit plan for this member",
        "I need the current coverage summary of the plan",
        "fetch the plan-level benefit snapshot",
        "tell me the key details of the member's current plan",
        "generate a summary of what the plan includes today",
        "list the plan's current benefit highlights",
        "provide a quick overview of this member's plan",
        "what benefits are active on the member's plan right now",
        "show a high-level breakdown of the plan benefits",
        "display the plan's current configuration at a glance",
        "I want to see the plan summary for this member",
        "give me the present state of the benefit plan",
        "retrieve the current plan benefit profile",
        "what is the plan's current coverage structure",
    ],

    "plan_history": [
        "show the change log of this member's benefit plan",
        "what modifications have been made to the plan over time",
        "list past revisions of the benefits plan",
        "display the audit trail of plan changes",
        "give me the timeline of updates to the plan",
        "retrieve the history of amendments to this member's plan",
        "when was the plan last modified",
        "pull up all historical edits on the benefit plan",
        "what changes occurred on the plan in previous versions",
        "fetch the revision log for the member's benefit plan",
        "tell me how the plan has evolved over time",
        "I need the chronological change record of the plan",
        "display every past update applied to the plan",
        "show the modification trail of the benefits plan",
        "list all prior versions of this member's plan",
        "what updates were made to the plan last year",
        "retrieve the plan's amendment history",
        "give me a timeline of benefit plan edits",
        "generate the historical change report for the plan",
        "trace all past changes to this member's benefit plan",
    ],

    "plan_finder": [
        "help me locate an available benefit plan",
        "search for plans that match this client",
        "which plans are offered to this member's group",
        "find a matching benefits plan",
        "look up what plans exist for this client",
        "discover available benefit plan options",
        "I need to find a plan that fits this member",
        "search the plan catalog",
        "what plans can be offered to this employer group",
        "find plan options available under the client",
        "identify eligible benefit plans",
        "locate the right plan for this member",
        "pull up plans that match the search criteria",
        "which benefit plans are currently offered",
        "show the list of available plan offerings",
        "look up plan choices for this client code",
        "discover plans that the member can enroll in",
        "search for benefit plans in the catalog",
        "help me find a suitable plan",
        "what plans should I consider for this client",
    ],

    # ──────────────────────────────────────────────────────────────────
    # claim_history_search intents  (generic phrasing, no hardcoded IDs)
    # ──────────────────────────────────────────────────────────────────
    "Refills": [
        "list refill counts across the member's prescriptions",
        "how many refills remain on the METFORMIN prescription",
        "display refill history for the member's maintenance drugs",
        "retrieve claims where refills were authorized",
        "which prescriptions have the most refills used",
        "show only the refill fills, not the initial fills",
        "tell me the refill status of the LISINOPRIL fills",
        "give me all claims marked as a refill",
        "pull up the refill timeline for chronic medications",
        "what refills are left on ATORVASTATIN",
        "fetch refill frequency for this member's claims",
        "are there any remaining refills for OMEPRAZOLE",
        "display claims that are on their second or later refill",
        "list prescriptions with zero refills remaining",
        "which drugs have exceeded their authorized refill count",
        "show refill-only claims for the member",
        "retrieve refill information across all active scripts",
        "how frequently has the member refilled GABAPENTIN",
        "give me a breakdown of initial fills versus refills",
        "which prescriptions are due for a refill soon",
    ],

    "DaysSupply": [
        "list claims with a 90 day supply",
        "filter claims where days supply equals 30",
        "which prescriptions were dispensed as a 14 day supply",
        "show fills with an extended 90-day supply window",
        "retrieve short-supply claims of 7 days or less",
        "give me claims dispensed for 60 days",
        "display only 28 day supply prescriptions",
        "find claims with days supply greater than 84",
        "pull up 21 day supply fills",
        "which claims had a 180 day supply",
        "tell me prescriptions dispensed for less than 15 days",
        "fetch claims where the supply length is 45 days",
        "list all 10 day supply fills",
        "show claims with a days-supply between 25 and 35",
        "what fills were for a 3 day emergency supply",
        "give me extended-supply 90-day maintenance claims",
        "display 120 day supply fills for this member",
        "retrieve claims dispensed on a 5 day supply",
        "which fills had exactly a 30-day supply",
        "list claims grouped by days supply duration",
    ],

    "PriorAuth": [
        "which claims required prior authorization",
        "show fills that went through a PA process",
        "did HUMIRA need prior authorization for this member",
        "list claims where PA was approved",
        "retrieve prescriptions with an active prior auth on file",
        "display PA-approved claims for specialty drugs",
        "tell me if the ELIQUIS fills needed prior auth",
        "fetch claims that had a PA override applied",
        "pull up prescriptions with pending prior authorization",
        "give me claims where PA was denied",
        "what prescriptions bypassed the PA requirement",
        "show prior authorization outcomes for the member",
        "list claims currently awaiting PA approval",
        "which drugs processed under a Smart PA",
        "display PA-expired prescriptions",
        "retrieve claims where member PA was on file",
        "find fills that required clinical prior authorization",
        "which recent claims went through PA adjudication",
        "show claims gated by a prior authorization requirement",
        "tell me which specialty fills had PA on file",
    ],

    "Diagnosis": [
        "show claims with diagnosis code E11.9",
        "filter claims by ICD-10 J45.909",
        "which claims carry diagnosis I10",
        "retrieve fills linked to diagnosis code F32.9",
        "display claims tagged with ICD code M54.16",
        "list prescriptions associated with diagnosis K21.00",
        "give me claims for diagnosis code G47.00",
        "fetch claims where the ICD-10 is Z79.82",
        "show all claims filed under diagnosis N18.3",
        "pull up claims with ICD R06.00",
        "what fills map to diagnosis code E78.5",
        "list claims carrying ICD-10 B02.9",
        "retrieve claims tagged with diagnosis L40.50",
        "display prescriptions linked to diagnosis D64.9",
        "filter by diagnosis code C50.911",
        "which claims were billed with ICD M79.12",
        "get claims submitted with diagnosis R10.13",
        "show me claims carrying diagnosis code J06.9",
        "find claims associated with ICD-10 E08.00",
        "list prescriptions for diagnosis code F41.1",
    ],

    "Settlement": [
        "show claims with settlement code 358",
        "filter by settlement code 001",
        "which claims returned settlement code 425",
        "retrieve claims with pharmacy settlement response 200",
        "list fills that received settlement code 310",
        "display claims tagged with settlement 099",
        "give me claims where the settlement code is 750",
        "fetch claims closed under settlement code 112",
        "pull up claims with settlement response 500",
        "tell me which fills carry settlement 044",
        "list claims returning settlement code 275",
        "retrieve pharmacy settlement code 633",
        "what claims had settlement code 088",
        "display claims with settlement equal to 190",
        "show fills that returned settlement 560",
        "filter claims by settlement response code 721",
        "fetch claims carrying settlement code 015",
        "find claims tagged with settlement 840",
        "which claims settled with code 403",
        "give me claims whose settlement code is 225",
    ],

    "PharmType": [
        "show claims filled at retail pharmacies",
        "filter claims dispensed through mail-order channels",
        "list specialty pharmacy claims for this member",
        "which fills came from a retail chain pharmacy",
        "retrieve claims processed through mail-order",
        "display claims filled via the specialty pharmacy channel",
        "give me fills from long-term care pharmacy settings",
        "fetch compounding pharmacy claims",
        "show claims dispensed by home infusion pharmacy type",
        "pull up mail-service 90-day fills",
        "which claims used the specialty pharmacy channel",
        "list claims from independent retail pharmacies",
        "tell me which fills came from institutional pharmacy type",
        "retrieve claims filled via nuclear pharmacies",
        "display managed-care pharmacy channel claims",
        "filter by clinic pharmacy dispensing type",
        "give me fills categorized as retail",
        "which pharmacy type dispensed the most claims",
        "show only mail-order channel prescriptions",
        "list claims grouped by pharmacy channel category",
    ],

    "Plan": [
        "show claims processed under plan LICS2",
        "filter claims by plan code RX8B",
        "which claims were adjudicated under plan MED3",
        "retrieve fills under insurance plan STD2",
        "list claims covered by plan FRM1",
        "display claims associated with plan HMO1",
        "give me fills under plan EPO3",
        "fetch claims belonging to plan PPO7",
        "show all claims under plan HSA2",
        "pull up claims for benefit plan LTC5",
        "tell me which fills are under plan N023D",
        "list claims filed against plan V033A",
        "retrieve claims for plan code T082C",
        "display claims associated with plan RET4",
        "which claims ran through plan D061A",
        "get fills processed under plan K044B",
        "show claims under plan G077B",
        "filter by insurance plan J029C",
        "fetch claims under plan LICSX",
        "list claims adjudicated under a specific insurance plan",
    ],

    "Pharmacy": [
        "show claims filled at CVS PHARMACY 00610",
        "list fills dispensed by WALGREENS 04528",
        "retrieve claims from RITE AID 11237",
        "which fills were filled at TARGET PHARMACY 01893",
        "display claims from KROGER PHARMACY 05672",
        "give me claims processed at WALMART PHARMACY 10340",
        "fetch fills dispensed by COSTCO PHARMACY 09185",
        "show claims from PUBLIX PHARMACY 03419",
        "pull up fills filled at HEB PHARMACY 06821",
        "tell me which claims came from SAFEWAY PHARMACY 08756",
        "list claims from ALBERTSONS PHARMACY 02947",
        "retrieve claims filled at SAM'S CLUB PHARMACY 11502",
        "display fills dispensed by WEGMANS PHARMACY 07083",
        "get claims from MEIJER PHARMACY 04291",
        "show fills at GIANT EAGLE PHARMACY 08134",
        "which claims were processed at STOP AND SHOP PHARMACY 05068",
        "fetch fills from WINN-DIXIE PHARMACY 01756",
        "find claims dispensed at FRED MEYER PHARMACY 09423",
        "pull up fills from HARRIS TEETER PHARMACY 03580",
        "give me claims filled at HANNAFORD PHARMACY 06214",
    ],

    "Prescriber": [
        "show claims by prescriber NOEUV",
        "list claims written by Dr. PATEL",
        "retrieve fills prescribed by NPI 1234567890",
        "which claims were ordered by prescriber SMITH",
        "display claims from prescriber Dr. JOHNSON",
        "give me claims by provider NPI 9876543210",
        "fetch claims prescribed by Dr. WILLIAMS",
        "show all fills by prescriber GARCIA",
        "pull up claims ordered by NPI 4567891230",
        "tell me which claims Dr. MARTINEZ prescribed",
        "list fills from prescriber NPI 7891234560",
        "retrieve claims by Dr. ANDERSON",
        "display fills written by prescriber TAYLOR",
        "get claims prescribed by NPI 3216549870",
        "show claims from Dr. THOMAS",
        "which fills were by prescriber NPI 6549873210",
        "fetch claims ordered by Dr. ROBINSON",
        "find claims by prescriber HERNANDEZ",
        "pull up claims from provider NPI 2583691470",
        "give me claims written by Dr. NGUYEN",
    ],

    "Pricing": [
        "how much did the member pay for LEVOTHYROXINE",
        "what was the copay on METFORMIN fills",
        "show the out-of-pocket cost for ATORVASTATIN",
        "retrieve the ingredient cost of LISINOPRIL claims",
        "display patient-pay amount for AMLODIPINE",
        "give me the total cost of OMEPRAZOLE prescriptions",
        "what did the plan pay for GABAPENTIN",
        "fetch the dispensing fee on LOSARTAN fills",
        "tell me the member cost-share for SERTRALINE",
        "how much was the coinsurance on MONTELUKAST",
        "retrieve the usual and customary price for PANTOPRAZOLE",
        "display the plan-paid amount for ESCITALOPRAM",
        "what was the ingredient cost plus fee for CLOPIDOGREL",
        "get the member responsibility amount for ROSUVASTATIN",
        "show me the AWP for DULOXETINE claims",
        "what MAC price was applied to TAMSULOSIN",
        "fetch the total charge for ALBUTEROL prescriptions",
        "tell me the net cost after rebate for JANUVIA",
        "list member pay details for ELIQUIS",
        "what was the cost breakdown on the HYDROCHLOROTHIAZIDE fill",
    ],

    "Status": [
        "show all rejected claims for this member",
        "list claims in paid status",
        "which claims are currently pending",
        "display all denied claims",
        "retrieve claims that were successfully adjudicated",
        "give me claims in reversed status",
        "fetch all approved claims",
        "show claims that failed during adjudication",
        "pull up claims in submitted status",
        "tell me which claims are partially paid",
        "list claims with a captured status",
        "display claims that were overridden and paid",
        "which claims show a suspended processing state",
        "get claims with a duplicate status",
        "show claims currently in review",
        "retrieve all voided claims for this member",
        "filter claims by adjusted status",
        "fetch claims with reprocessed status",
        "find claims currently in hold state",
        "display all claims in closed status",
    ],

    "RejectCode": [
        "show claims with reject code 79",
        "filter claims by rejection code 75",
        "which claims have NCPDP reject code MR",
        "retrieve claims with reject code 70",
        "list claims rejected under code 76",
        "display claims carrying reject code NN",
        "give me claims with rejection code 88",
        "fetch claims rejected with code ET",
        "show claims with reject code 65",
        "pull up claims having rejection code PA",
        "tell me which claims got reject code 7D",
        "list claims with NCPDP reject code DG",
        "retrieve claims rejected with code M1",
        "display claims with rejection response code 78",
        "what claims had reject code QE",
        "get claims with reject code 3G",
        "show claims carrying rejection code FQ",
        "filter by reject code 69",
        "fetch claims with rejection code RE",
        "find claims with reject code 8C",
    ],

    "DrugLast": [
        "when was LEVOTHYROXINE taken last for this member",
        "what is the most recent fill date for METFORMIN",
        "show the last time ATORVASTATIN was dispensed",
        "when did this member last get LISINOPRIL",
        "retrieve the latest dispensing date for AMLODIPINE",
        "display the most recent OMEPRAZOLE fill",
        "how recently was GABAPENTIN filled",
        "fetch the last fill date for LOSARTAN",
        "tell me when SERTRALINE was last picked up",
        "show the latest claim for HYDROCHLOROTHIAZIDE",
        "when was the last MONTELUKAST dispensed",
        "pull up the most recent PANTOPRAZOLE fill",
        "give me the last dispensed date for ESCITALOPRAM",
        "what was the latest fill for CLOPIDOGREL",
        "retrieve the last time ROSUVASTATIN was filled",
        "display when DULOXETINE was most recently dispensed",
        "how long ago was TAMSULOSIN last filled",
        "show the latest dispense record for ALBUTEROL",
        "when did this member last receive JANUVIA",
        "fetch the most recent ELIQUIS fill date",
    ],

    "Month": [
        "give me all claims for this member in january",
        "show fills from february",
        "retrieve march claims for this member",
        "list claims filed in april",
        "display fills from the month of may",
        "fetch june claims",
        "pull up claims for july",
        "show claims from august",
        "get all september fills for this member",
        "tell me claims processed in october",
        "list fills dispensed in november",
        "retrieve december claims",
        "which claims were filled during march",
        "display all claims from last january",
        "give me february prescription fills",
        "show claims for the month of june",
        "fetch claims from october",
        "pull up all april fills",
        "what claims does this member have in september",
        "list fills during the month of november",
    ],

    "ClaimNum": [
        "claim number 260302639954275",
        "look up claim 480517832091643",
        "retrieve claim number 710924356178502",
        "show details for claim 392081547623918",
        "fetch claim 853746291035824",
        "get claim number 124509873642156",
        "display claim 567832410298745",
        "find claim number 938271456082319",
        "pull up claim 641285739401562",
        "tell me about claim number 205638914720483",
        "what is this claim 879143265098712 about",
        "retrieve information for claim 412067593841205",
        "show claim 736502918374621",
        "look up claim number 198345672081534",
        "fetch details for claim 523781094265130",
        "get information on claim number 847216305492871",
        "display claim number 309854176230948",
        "find claim 671093248157603",
        "pull up claim number 985412370648215",
        "show claim 453278619034527",
    ],

    "NDC": [
        "NDC 33342-0395-44",
        "look up NDC 00071-0155-23",
        "show claims for NDC 68462-0235-90",
        "retrieve claims with NDC 00093-5057-01",
        "filter by NDC 16729-0044-15",
        "fetch claims for NDC 31722-0710-30",
        "display claims with NDC 65862-0198-90",
        "find claims matching NDC 00378-1805-01",
        "get claims by NDC 42794-0018-10",
        "pull up NDC 50090-2188-00",
        "list claims for NDC 69097-0833-07",
        "tell me about NDC 51991-0747-33",
        "show claims with NDC 00591-0405-01",
        "retrieve NDC 43547-0351-11 claims",
        "which claims have NDC 00781-5180-01",
        "fetch claims with NDC 62332-0076-31",
        "display NDC 55111-0683-30 claim records",
        "search for NDC 13668-0095-90",
        "look up claims by NDC 00054-0163-25",
        "find claims for NDC 72205-0028-90",
    ],

    "Manufacturer": [
        "manufactured by MACLEODS",
        "show claims for drugs made by TEVA",
        "filter claims by manufacturer MYLAN",
        "which claims have drugs from PFIZER",
        "retrieve claims for manufacturer NOVARTIS",
        "list claims with medications by SANDOZ",
        "display claims for drugs manufactured by ABBVIE",
        "give me claims from manufacturer MERCK",
        "fetch claims for drugs by AUROBINDO",
        "show all claims with manufacturer LUPIN",
        "pull up claims for medications from DR REDDY",
        "tell me which claims are from manufacturer AMNEAL",
        "list claims with drugs by SUN PHARMA",
        "retrieve manufacturer CIPLA claims",
        "display claims from drug maker APOTEX",
        "get claims for drugs manufactured by HIKMA",
        "show claims by manufacturer GLENMARK",
        "filter by manufacturer ZYDUS",
        "fetch claims with drugs from ALKEM",
        "find claims for manufacturer TORRENT",
    ],

    "Generic": [
        "show all generic drug claims",
        "list only non-branded medication fills",
        "filter claims for generic substitutions",
        "which fills dispensed a generic equivalent",
        "retrieve claims where a generic was substituted for a brand",
        "display generically dispensed prescriptions",
        "give me claims flagged as generic",
        "fetch claims for unbranded medications",
        "show multi-source generic fills",
        "pull up claims dispensed with generic alternatives",
        "tell me which prescriptions were filled generically",
        "list claims dispensed as generic substitutes",
        "retrieve AB-rated generic claims",
        "display claims where a therapeutic generic was chosen",
        "get claims with generic equivalent dispensed",
        "show off-patent drug claims",
        "filter to show only generic fills",
        "which claims used a bioequivalent generic",
        "fetch non-proprietary drug claims",
        "find claims dispensed with generic formulations",
    ],

    "Brand": [
        "show brand name claims",
        "list claims for proprietary medications",
        "filter claims dispensed as trade name drugs",
        "which fills used the original brand product",
        "retrieve claims for innovator brand drugs",
        "display brand-only dispensed prescriptions",
        "give me claims where the branded version was filled",
        "fetch claims flagged as trade name",
        "show single-source brand fills",
        "pull up claims for patented brand medications",
        "tell me which prescriptions were dispensed as brand",
        "list claims for name-brand pharmaceuticals",
        "retrieve claims where brand was medically necessary",
        "display branded product claims with DAW codes",
        "get claims for proprietary formulation drugs",
        "show brand-dispensed claims only",
        "filter to show only branded prescription fills",
        "which claims had an innovator product dispensed",
        "fetch trade name medication claims",
        "find claims where the label brand was dispensed",
    ],
}
    DOMAIN_REGISTRY = {
        "benefits_api": {
        "name": "Benefits API",
        "description": (
            "Member benefits API: benefit phase and coverage tier, audit trail and change history, approval details including transition fill (TF), plan overrides, and BPG configuration."
        ),
        "api_endpoint": "/myclaims/benefits/v1/member",
        "intents": [
            "plan_summary",         # Summary of benefits plan
            "plan_history",         # History of benefits plan
            "plan_finder",          # Find a benefits plan
        ],
    },
    "claim_history_search": {
        "name": "Claim History Search",
        "description": (
            "Claim history and drug search API: searching claims by date range, drug information lookups, fill date queries, drug interaction reviews (DUR), and compound medication details."
        ),
        "api_endpoint": "/myclaims/claims/v1/claim/history",
        "intents": [        
            "Refills",              # Claims with refill information
            "DaysSupply",           # Claims with days supply details
            "PriorAuth",            # Claims with prior authorization status
            "Diagnosis",            # Claims with specific diagnosis codes
            "Settlement",           # Claims with settlement codes
            "PharmType",            # Claims filtered by pharmacy type
            "Plan",                 # Claims under specific insurance plans
            "Pharmacy",             # Claims from specific pharmacies
            "Prescriber",           # Claims by specific prescribers
            "Pricing",              # Claims with detailed pricing information
            "Status",               # Claims with specific status (e.g., rejected)
            "RejectCode",           # Claims with specific rejection codes
            "DrugLast",             # Claims with information on the last dispensed drug
            "Month",                # Claims filtered by month
            "ClaimNum",             # Claims by specific claim number
            "NDC",                  # Claims by drug NDC
            "Manufacturer",          # Claims by drug manufacturer
            "Generic",              # Claims for generic drugs
            "Brand"              # Claims for brand name drugs  
        ]
    },
    "cap_api": {
        "name": "Cap-API",
        "description": (
            "Capability API for single-claim operations: claim status, pricing, pharmacy details, prescriber information, rejection analysis, settlement codes, reversals, coordination of benefits, reimbursement, prescription details, and generic alternatives."
        ),
        "api_endpoint": "/myclaims/claims/v1/claim/byclaimnumber",
        "intents": [
            "claim_status",         # General claim summary / adjudication outcome
            "multi_claim_summary",  # Summary of ALL claims for a member
            "pharmacy_info",        # Dispensing pharmacy details
            "prescriber_info",      # Prescribing physician details
            "pricing_info",         # Copay, ingredient cost, patient pay
            "reimbursement_info",   # Amount paid TO the pharmacy
            "rejection_reasons",    # Why the claim was denied + resolution steps
            "settlement_info",      # Pharmacy response/feedback codes
            "rx_details",           # RX number, quantity, days supply
            "reversal_info",        # Reversals, R&R, manual adjustments
            "cob_info",             # Coordination of Benefits / dual coverage
            "generic_availability", # Generic alternatives / therapeutic equivalents
        ],
    },
    "general": {
        "name": "General",
        "description": (
            "Non-API intents: greetings, help requests, and queries unrelated to pharmacy claims."
        ),
        "api_endpoint": None,
        "intents": [
            "greeting",             # Hello, hi, welcome
            "help",                 # How to use the system
            "out_of_scope",         # Unrelated queries
        ],
    },
}